### ISSUE TITLE
Give credit to the original author?

### ISSUE THREAD

**Issue by dynamix** [kelindar/bitmap#8]
Thanks for creating a usable Go bitmap index library! One thing I noticed while I was reading through the code: parts of the heavy lifting (AVX code generation) seems similar to code from a talk given by @mkevac (https://m.youtube.com/watch?v=WvlUH6MjUuI) and his examples https://github.com/mkevac/gopherconrussia2019/tree/master/simplesimd - with many identical lines (https://github.com/mkevac/gopherconrussia2019/blob/master/simplesimd/asm.go#L106 vs https://github.com/kelindar/bitmap/blob/main/generate/amd64.go#L104). If it was actually copied I think it would be fair to give the original author some credit, especially given that he has not put the code under any official licence and the files in this repo all contain `Copyright (c) Roman Atachiants` 😏. If it wasn't mea culpa.

**Comment by kelindar** [comment]
@dynamix You are correct, the original generator code was inspired by that work. Let me add it in the header.
